# Site settings
author: Thanapat Veerakajorn
title: Tracking Thought
header-img: img/home-bg.png
email: t.veerakajorn@gmail.com
copyright_name: Thanapat Veerakajorn
description: > # this means to ignore newlines until "baseurl:"
  Experiences
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  tvee24537

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
